### ISSUE TITLE
Export of CSV from qiime micom fit-phenotype visualization

### ISSUE THREAD

**Issue by Mechah** [micom-dev/q2-micom#10]
It seems as if the direct export of .qzv results obtained with the qiime micom fit-phenotype command in CSV format does not work.
I tried with different browsers (chrome, firefox, edge). Either it takes really long or it is not working.
Thanks for fixing - if there is something to fix here ;-)

**Comment by cdiener** [comment]
Hi, what version of the plugin are you running? If it's not 0.10.0 updating is likely to fix that due to the fix for https://github.com/micom-dev/q2-micom/issues/7 deployed with it.

**Comment by Mechah** [comment]
Oh I'll update and check again.
