### ISSUE TITLE
Indicate supported CPLEX versions in the installation instructions

### ISSUE THREAD

**Issue by afvrbanac** [micom-dev/q2-micom#11]
Hello, I'm having a difficult time trying to install the python API. I downloaded CPLEX for Linux x86-64 (part # CC8ATML) and it appears to only come with folders for python 3.7 and 3.8, so I cannot run this command from the set-up instructions:

pip install ibm/cplex/python/3.6/x86-64_linux

If I try to do the 3.7 folder I get the error:
Exception: this 'cplex' package (version 20.1.0.0) is not compatible with this version of Python: expected 3.7 but got 3.6

I've tried many ways to get it to work with the Q2 2020.11 conda env (the main setup.py script, adding it to the python path), but is says there are incompatibilities. I was able to just pip install the free version of cplex and build models, but I get this error when trying to use micom-grow and tradeoff:

 "All numerical optimizations failed. This indicates a problem "
cobra.exceptions.OptimizationError: All numerical optimizations failed. This indicates a problem with the solver or numerical instabilities. Check that you have CPLEX or Gurobi installed. You may also increase the abundance cutoff to create simpler models."

I assume this is related to having the free version of CPLEX. 

Is there some way to access the python 3.6 version of CPLEX? Or another way you recommend I try to install it?

**Comment by afvrbanac** [comment]
Note: I downloaded an earlier version of CPLEX (V12.6.1) and it came with a python 3.6 folder. I was able to get it to install in the Q2 2020.11 conda env and was able to run micom-grow without errors using this older version of CPLEX.

**Comment by cdiener** [comment]
Good point, we should state which versions will work. FYI the last cplex version still supporting Python 3.6 should be 12.10.

**Comment by afvrbanac** [comment]
That appears to be the current version and what I downloaded for both Mac and Linux. Both were missing python 3.6. It says the date posted is 11 Dec 2020 on IBMs website so maybe they made some changes to 12.10?

**Comment by cdiener** [comment]
I think what you are describing is version 20.1.0 not 12.10.0. Version 12.10.0 was released Dec 6, 2019.

**Comment by afvrbanac** [comment]
Ah right sorry, my brain read it backwards!
