### ISSUE TITLE
Filtering samples from models for fit-phenotype

### ISSUE THREAD

**Issue by afvrbanac** [micom-dev/q2-micom#12]
Hi, back again! I was wondering, is it possible to filter or subset samples from already built models? From what I understand they are built for each sample individually. I ask because I want to run fit-phenotype on different subsets of data (I have longitudinal data and want to look at individual time points). Of course I could just run the whole pipeline for feature tables from each timepoint, but I wanted to see if I could save time by filtering. Thanks!

**Comment by cdiener** [comment]
Yep, you are right. `build` and `grow` treat each sample independently and results are not compared until visualization. There is currently no action that allows subsetting but I think it's a good idea and I'll add it. There are other use cases apart from longitudinal data where that may be useful. 

The strategy you outlined (running on feature tables for each subset) works as well though. If the subsets are mutually exclusive this will take the same time for model building and simulation. So running 4x10 samples should take pretty much as long as running 40 samples.

**Comment by afvrbanac** [comment]
Awesome that would be great. The option to combine models would be nice too for those who are compute-limited. I got an error halfway through trying to run 400 samples at once which looked like it was just too much for my computer, so I ended up breaking up the feature table into smaller subsets which ran fine.

**Comment by cdiener** [comment]
Okay, so we would probably need an option for subsetting models and growth results. Makes sense.

**Comment by cdiener** [comment]
This is now available in version 0.11.0 or higher. See https://micom-dev.github.io/q2-micom/#filtering-built-community-models-or-simulation-results.
