### ISSUE TITLE
mismatch of IDs between models and diet

### ISSUE THREAD

**Issue by Mechah** [micom-dev/q2-micom#13]
Hi, I want to run micom 0.10.1 on the carveme_refseq84_genus.qza and the western_diet_gut_carveme.qza artifacts.
The model was created without any errors, but when I run the micom tradeoff command:

qiime micom tradeoff --i-models micom_0_10_1_carveme_genus_models.qza --i-medium western_diet_gut_carveme.qza --p-threads 16 --o-results micom_0_10_1_carveme_genus_tradeoff.qza --verbose

I receive the following error: No ID from the medium could be found in the exchange reactions. This means you probably have mismatched IDs...

Is there any known mismatch between the carveme metabolic community models and their respective carveme diet model?

Thanks again for any help and happy Easter!

**Comment by cdiener** [comment]
Can you update micom in your qiime environment? That should have been fixed in version 0.22.2. 

```python
pip install -U micom
```

**Comment by Mechah** [comment]
I did the update with pip, but received the same error when I run qiime micom tradeoff again. 
Maybe this issue has been fixed in the python package but not the q2-plugin of micom?

**Comment by cdiener** [comment]
`q2-micom` is just a wrapper for the `micom.workflow` steps. I just tried and it worked for me. Have you rebuilt your model before checking? If that would be too much effort you can also modify the medium so the reactions end with `_e_m` instead of `_m`. However if you rebuilt the models it should just work out of the box with micom>=0.22.

**Comment by Mechah** [comment]
Sorry I forgot to rebuilt the models as well...  Everything is working now and it is great to see the increase of predictions with the carveme database and its models :-)
Thanks for your help!

**Comment by cdiener** [comment]
Awesome, glad to hear it!
