### ISSUE TITLE
Comparability between humans and mice

### ISSUE THREAD

**Issue by Mechah** [micom-dev/q2-micom#15]
Hi I was wondering if it makes any sense to use micom also for amplicon data from mouse fecal samples. Did you ever test how far micom's metabolic predictions could be extrapolated to the system of mice?
Thanks for any discussions...

**Comment by cdiener** [comment]
Not really but it should extend there. One could use a deep metagenomic data set from mice to run the same validation (growth rates vs. replication rates) as in the paper. Question is how well AGORA represents taxa from the mouse gut on the species and genus levels. Diet could be easier as mouse chow might be more standardized than a human diet.

**Comment by Mechah** [comment]
Sounds reasonable to me.
Thanks again for your input!
