### ISSUE TITLE
Error when filtering built community models and simulation results

### ISSUE THREAD

**Issue by Mechah** [micom-dev/q2-micom#16]
First of all thanks for including the new functionality to filter existing community models and simulation results!
I tried both qiime micom filter-results and qiime micom filter-models, but in each case I get the following error message:

Plugin error from micom:
  'Metadata' object has no attribute 'copy'

I tested different metadata files and validated those metadata files with keemei. So I'm kind of stucked at the moment...

By the way there is a typo in the community tutorial on how to filter results - it should be:

qiime micom filter-**results** --i-results growth.qza \
                          --m-metadata-file metadata.tsv \
                          --p-query "status == 'Cancer'" \
                          --o-filtered-**results** cancer_results.qza

Thanks again for your help!

**Comment by cdiener** [comment]
Yep, this is a bug. I'll get to fixing it.

**Comment by cdiener** [comment]
Okay now fixed in 0.11.3.

**Comment by Mechah** [comment]
That was quick!
Perfect thanks :-)
