### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by said3427** [micom-dev/q2-micom#2]
I had some issues during installation:

FileNotFoundError: [Errno 2] No such file or directory: '/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg'

Solved using:
`touch /home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg`

Also:

> Traceback (most recent call last):
>   File "/home/said/anaconda3/envs/qiime2-dev/bin/pip", line 10, in <module>
>     sys.exit(main())
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 75, in main
>     return command.main(cmd_args)
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 105, in main
>     return self._main(args)
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
>     self.handle_pip_version_check(options)
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 146, in handle_pip_version_check
>     timeout=min(5, options.timeout)
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 91, in _build_session
>     index_urls=self._get_index_urls(options),
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_internal/network/session.py", line 241, in __init__
>     self.headers["User-Agent"] = user_agent()
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_internal/network/session.py", line 159, in user_agent
>     setuptools_version = get_installed_version("setuptools")
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 619, in get_installed_version
>     working_set = pkg_resources.WorkingSet()
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
>     self.add_entry(entry)
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
>     for dist in find_distributions(entry, True):
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1983, in find_eggs_in_zip
>     if metadata.has_metadata('PKG-INFO'):
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1414, in has_metadata
>     return self._has(path)
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1854, in _has
>     return zip_path in self.zipinfo or zip_path in self._index()
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1731, in zipinfo
>     return self._zip_manifests.load(self.loader.archive)
>   File "/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1688, in load
>     mtime = os.stat(path).st_mtime
> FileNotFoundError: [Errno 2] No such file or directory: '/home/said/anaconda3/envs/qiime2-dev/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg'

Which I solved using:

`conda install tqdm==4.7.2`

Maybe you can specify that version in the tutorial.

**Comment by cdiener** [comment]
That's odd. I observed exactly the opposite problem where I had to install tqdm>=4.14 since micom requires that. I'll definitely update the installation requirements to make this more robust though.

**Comment by cdiener** [comment]
I updated the installation instructions in the community tutorial and Github repo. Could you try with those in a fresh environment. Also `q2-micom` will no explicitly warn if there is a solver mismatch.
