### ISSUE TITLE
Typo in the installation steps?

### ISSUE THREAD

**Issue by kf-cuanschutz** [micom-dev/q2-micom#33]
Hi,

in the installation steps described did you mean:

```
conda env update -n qiime2-2024.2 -f q2-micom.yml
```
as opposed to 
```
conda env update -n qiime2-2024.2 -f q2-micom-linux.yml
```

Thanks!

**Comment by cdiener** [comment]
Definitely. Leftover from the transition to a unified conda env file. Feel free to send in a PR, otherwise I'll fix it. Thanks!

**Comment by kf-cuanschutz** [comment]
Thank you! I just submitted a PR.
