### ISSUE TITLE
qiime with guobi optimization for only 1 user?

### ISSUE THREAD

**Issue by kf-cuanschutz** [micom-dev/q2-micom#37]
#### Problem description

Hi, trying to follow this [tutorial](https://micom-dev.github.io/q2-micom/) on qiime2 micom testing with gurobi optimization.
The software was installed in a shared filesystem. A different user than the person who installed the software ran the following miicom tradeoff command:

```bash
qiime micom tradeoff --i-models models.qza \
                     --i-medium western_diet_gut_agora.qza \
                     --p-threads 1 \
                     --o-results tradeoff.qza \
                     --verbose
```

The user got the following error:

```bash
problem = gurobipy.read(tmp_file_name)
File "src/gurobipy/gurobi.pxi", line 3779, in gurobipy.read
File "src/gurobipy/gurobi.pxi", line 112, in gurobipy.gurobi.read
File "src/gurobipy/gurobi.pxi", line 60, in gurobipy.gurobi._getdefaultenv
File "src/gurobipy/env.pxi", line 70, in gurobipy.Env.__init__
gurobipy.GurobiError: User name mismatch (licensed to 'kfotso@xsede.org', current user is 'stanislm@xsede.org')
```
The issue does not occur when the user who installed the package is running the software. Can more than one user run the software? In other words can I add more than one user into the license file? Can I give more than 1 hostname? Because we are working on an HPC cluster.

Thanks!

**Comment by cdiener** [comment]
Hi, sorry for he late reply (vacay). Personal licenses can not be shared as far as I know. You could try with a WLS license or a site license. For HPC/docker we usually use the WLS license, though you will have to renew it regularly.
