### ISSUE TITLE
Error when trying to map tutorial data to species models

### ISSUE THREAD

**Issue by cgj-tang** [micom-dev/q2-micom#9]
Hi there,

I am trying to build community models using the tutorial data provided, but rather than using the genus-specific models I've taken the species-specific ones from the linked provided (https://zenodo.org/record/3755182#.X7lx0M1Kg2w)

I get this error message after running `qiime micom build` though:

```
Merged with the database using ranks: species
Traceback (most recent call last):
  File "/home/chris/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/commands.py", line 329, in __call__
    results = action(**arguments)
  File "<decorator-gen-247>", line 2, in build
  File "/home/chris/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/home/chris/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/chris/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2_micom/_build.py", line 67, in build
    tax = build_spec(abundance, taxonomy, models, cutoff, strict)
  File "/home/chris/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2_micom/_build.py", line 53, in build_spec
    round(stats["mean"]), round(stats["std"]))
ValueError: cannot convert float NaN to integer

Plugin error from micom:

  cannot convert float NaN to integer
```

Building the models at the genus level works fine. Any ideas?

Thanks,
Chris

**Comment by cdiener** [comment]
Hi Chris,

The tutorial data is 16S amplicon data and has no species-level classifications. So nothing can be mapped on the species-level and the error you are seeing is due to that. I'll add a better error message for that case.

**Comment by cgj-tang** [comment]
HI Christian,
Thanks for getting back. I'm looking in the taxonomy file in the tutorial data - there definitely are species-level classifications that overlap with the models though. Like this one: 
`

c73b6b7f592410e11c536d42a8e01b99 | D_0__Bacteria;D_1__Bacteroidetes;D_2__Bacteroidia;D_3__Bacteroidales;D_4__Bacteroidaceae;D_5__Bacteroides;D_6__Bacteroides   thetaiotaomicron | 0.708355
-- | -- | --


`

**Comment by cdiener** [comment]
Hm, but those should only be present for a few taxa. In this case, I think the naming is the issue. MICOM expects the species to be `thetaiotamicron` and not `Bacteroides thetaiotamicron`. I'll see if I can detect that formatting and adjust when using species data.

**Comment by Mechah** [comment]
Hi, I get the same error when I run the qiime micom build command for genus level on a filtered feature-table . The original table did not result in any error, so I was wondering if missing (sample-ids) feature-ids could be an issue in my case? Or do you think my error is also associated to the naming of the lineages in my taxonomy file?

Plugin error from micom:

  cannot convert float NaN to integer

**Comment by cdiener** [comment]
I don't think that's related except for the observation that you get an empty taxonomy table. Do you have a reproducible example? You can verify in Python if your table is empty with:

```python
from micom.taxonomy import qiime_to_micom
qiime_to_micom("feature_table.qza", "taxa.qza")
```

**Comment by Mechah** [comment]
Indeed I get an empty data frame with these python commands.
Taxonomy was assigned with Silva138.
I realized that the recent version of q2-micom now allows filtering of models and results - awesome! This new feature could solve my problem. However, I got errors again. I'll open a separate issue to troubleshoot this topic...
